### ISSUE TITLE
shape '[47, 156, 4]' is invalid for input of size 29952

### ISSUE THREAD

**Issue by RDXiaoLu** [aeolusguan/NMRF#8]
python main.py --checkpoint-dir checkpoints/kitti_NRMFswin --config-file configs/kitti_mix_train_swint.yaml --num-gpus 4 SOLVER.RESUME pretrained/sceneflow/sceneflow_swint.pth  

When Start validation
Traceback (most recent call last):
  File "/mnt/hdd/yuanhui/NMRF-main/main.py", line 488, in <module>
    launch(
  File "/mnt/hdd/yuanhui/NMRF-main/main.py", line 129, in launch
    mp.start_processes(
  File "/home/yuanhui/anaconda3/envs/dualcoop/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/yuanhui/anaconda3/envs/dualcoop/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/yuanhui/anaconda3/envs/dualcoop/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/mnt/hdd/yuanhui/NMRF-main/main.py", line 183, in _distributed_worker
    main_func(*args)
  File "/mnt/hdd/yuanhui/NMRF-main/main.py", line 461, in main
    result_dict = evaluate(model, cfg)
  File "/mnt/hdd/yuanhui/NMRF-main/main.py", line 310, in evaluate
    results_i = evaluation.inference_on_dataset(model, data_loader, evaluator)
  File "/mnt/hdd/yuanhui/NMRF-main/nmrf/utils/evaluation.py", line 229, in inference_on_dataset
    evaluator.process(inputs, outputs)
  File "/mnt/hdd/yuanhui/NMRF-main/nmrf/utils/evaluation.py", line 372, in process
    proposal = proposal.reshape(_im_h, _im_w, num_proposals)
RuntimeError: shape '[47, 156, 4]' is invalid for input of size 29952

**Comment by aeolusguan** [comment]
Thanks for your question. It is a minor bug caused by network strides. We have fixed it. Please try it.
